name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  cloud_firestore: 4.4.3
  get: 4.6.5
  google_sign_in: 6.0.1
  lottie: ^2.2.0
  introduction_screen: 3.1.6
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.5.2
  get_storage: 2.1.1
  intl: 0.17.0
  image_picker: 0.8.6+4
  firebase_storage: 11.0.15
  flutter_launcher_icons: 0.12.0
  flutter:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
  uses-material-design: true
